### ISSUE TITLE
Remove copy of code in the README

### ISSUE THREAD

**Issue by jakekarnes42** [Markay12/JavaLinkedList#2]
The README contains a [section](https://github.com/Markay12/JavaLinkedList/blob/master/README.md#below-is-the-basic-information-for-constructing-a-linked-list) with a slightly different version of the code. I would suggest removing the source code from the README.md file because it's difficult to maintain two separate copies like this. It's easy to get them out of sync. If you really want to share some of the code within the README, maybe you could link to the actual code within the repo?

**Comment by Markay12** [comment]
Awesome, I didn't know I could just link to the code like that. I will change it
